









1)数据的插入
①单记录的插入
USE  LMS
GO
SELECT  *  FROM  S
INSERT INTO  S(SNO, SNAME) VALUES('200300','Paulwen')
SELECT * FROM  S


②多记录的插入
CREATE  TABLE  SBAK(
SNO VARCHAR (10) NOT NULL,
SNAME VARCHAR(20),
DEPT VARCHAR(20), 
AGE INT, 
SEX CHAR(4))
GO
SELECT *  FROM  SBAK
INSERT  INTO  SBAK  SELECT *  FROM  S;
SELECT *  FROM  SBAK



2)数据的删除
CREATE  TABLE CBAK ( 
	CNO VARCHAR(10) NOT NULL, 
	CNAME VARCHAR(20), 
	CPNO VARCHAR(10),
	CREDIT INT)
GO
INSERT  INTO  CBAK  SELECT  *  FROM  C
DELETE  FROM  CBAK  WHERE  CREDIT<4
SELECT  *   FROM  CBAK


3)数据的修改
SELECT  *  FROM  S
UPDATE  S  SET  DEPT='CS'WHERE  DEPT='计算机系'
GO
SELECT  *  FROM  S


4)索引的建立
①建立非聚族索引
SELECT  *  FROM  C
GO
CREATE  INDEX  ICNAME  ON  C (CNAME)
GO
SELECT  *   FROM  C  /*看数据表 */
SELECT  *   FROM  C  with (INDEX= ICNAME)   /*按索引次序看数据表 */


②建立聚族索引
SELECT *  FROM  C
GO
CREATE  CLUSTERED  INDEX  CICNO  ON  C(CNO)
GO
SELECT *   FROM  C


③建立唯一索引
CREATE  UNIQUE  INDEX  UISNO  ON  SC (SNO)

执行后有什么结果？为什么会出现这个结果？
CREATE  UNIQUE  INDEX  UISNO  ON  SC (SNO,  CNO  DESC)

执行后有什么结果？

④建立复合索引
SELECT  *  FROM  S
GO
CREATE  INDEX  IAGESNO  ON  S(AGE DESC, SNO)
GO 
SELECT  *  FROM  S
SELECT  *  FROM  S WITH (INDEX =IAGESNO)


⑤查看表中的索引
SP_HELPINDEX  'S'


⑥删除表中的索引
DROP  INDEX  S.IAGESNO
GO
SP_HELPINDEX  'S'


5)视图及其操作
①视图的建立
CREATE  VIEW  SHOWSNO
	AS
	SELECT  S.SNO, SNAME, AVG(SCORE) AS 平均成绩 
	FROM  S, SC
	WHERE  S.SNO=SC.SNO
	GROUP BY S.SNO, SNAME
GO 
SELECT  *  FROM  SHOWSNO



创建信息系学生的视图
CREATE  VIEW  VISDEPT
AS
SELECT  *   FROM  S  WHERE  DEPT='信息系'


②在视图上修改数据
UPDATE  VISDEPT
SET  DEPT='IS'
GO 
SELECT  *  FROM  VISDEPT
视图中还有数据吗？为什么会这样？

CREATE  VIEW  S_SUM AS
	SELECT  SNO, SUM(SCORE)  AS  TOTALSCORE  FROM  SC
	GROUP  BY  SNO
GO
UPDATE  S_SUM SET TOTALSCORE=60

执行语句, 出现什么结果？分析为什么？

③在视图上删除数据
SELECT  *  FROM  VISDEPT
DELETE  FROM  VISDEPT  WHERE  SEX='女'
SELECT  *  FROM  VISDEPT
SELECT  *  FROM  S



1)将S表系部为“计算机系”学生对应的系部改为‘CS’。
UPDATE S SET DEPT='CS' WHERE DEPT='计算机系';


2)创建一个与SC表相同新数据表SCNEW，查询SC表中成绩为空的记录并将其复制到SCNEW表中。
create table SCNEW(
	SNO VARCHAR(10) NOT NULL,
	CNO VARCHAR(10) NOT NULL,
	SCORE DECIMAL
)
GO
INSERT INTO SCNEW SELECT * FROM SC WHERE SCORE IS NULL
SELECT * FROM SCNEW



3)删除SC表中成绩为空的选课记录。
DELETE FROM SC WHERE SCORE IS NULL
GO
SELECT * FROM SC


4)根据S表中姓名字段建立唯一性索引。
CREATE UNIQUE INDEX UISNAME ON S(SNAME)


5)建立S表上SNO的聚族索引。
CREATE CLUSTERED INDEX CISNO ON S(SNO)

6)建立SC表上根据SNO升序，CNO降序的复合索引。
CREATE INDEX IDX_SNO_CNO ON SC(SNO ASC, CNO DESC)


7)建立每门课程的课程号、课程名、选课人数、平均分的视图。
CREATE VIEW MYVIEW AS
	SELECT C.CNO, C.CNAME, COUNT(SC.CNO) 选课人数, AVG(SC.SCORE) 平均分
	FROM C
	LEFT OUTER JOIN SC
	ON C.CNO=SC.CNO
	GROUP BY C.CNO, SC.CNO, C.CNAME
GO
SELECT * FROM MYVIEW
